---
title: "data"
author: "Daniel(Kailun) Jin, John Ju"
format: html
editor: visual
embed-resources: true
---
```{r setup, include=FALSE}
library(tidyverse)
library(mosaic)
library(ggformula)
library(rethinking)
library(rstan)
library(CalvinBayes)
library(bayesplot)
library(tidybayes)
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      fig.width = 7, 
                      fig.height = 4)

theme_set(theme_minimal(base_size = 16))

cmdstanr::register_knitr_engine(override=FALSE)

```

# Dataset

```{r}
 data <- read.csv("Life Expectancy Data.csv")
 glimpse(data)
```

We found our data in kaggle website, our data is about the life expectancy for each country from 2000 to 2015. Here is our link.

[data source link](https://www.kaggle.com/datasets/kumarajarshi/life-expectancy-who?resource=download)

Research question: dose the percentage.expenditure has association the life expectancy.

response:Life.expectancy

key predictor:percentage.expenditure
